[project]
name = "browser-recall-weekly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.16"
dependencies = [
    "python-dotenv",
    "requests",
    "loguru",
    "wordcloud"
]
